version: "2"

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.10"

sphinx:
  configuration: source/conf.py

formats:
  - pdf

python:
  install:
    - requirements: requirements.txt

build:
  apt_packages:
    - latexmk
    - texlive-latex-extra
    - texlive-fonts-recommended
    - texlive-xetex
    - texlive-science  # Optional, adds extra LaTeX packages
